### ISSUE TITLE
enhancement : run suricata-verify against rpm installation

### ISSUE THREAD

**Issue by javabeanz** [jasonish/suricata-verify-old#15]
suricata-verify needs a suricata source directory but i want to run it against an rpm installation with emerging ruleset. the README could be adjusted to clearer specify the specific purpose of this project.

**Comment by jasonish** [comment]
Some changes could be made to run it against a Suricata binary without the source (ie. an RPM) - many tests would need to be skipped as the source is sometimes required to know what features are available in Suricata, especially between releases. 

But you'll have to be more clear on what you expect by running it against the emerging ruleset.

Each test, it somewhat like a unit test, but instead a verification test. Where a given set of inputs in is tested for expected output, primarily for development use to make sure code changes don't have unexpected changes to output, or have the expected changes to output.

**Comment by javabeanz** [comment]
maybe it is possible to make a subset (without need for sources) of all the tests to run againt the emerging ruleset ?

**Comment by jasonish** [comment]
What do you plan to test against the emerging ruleset? You'd still need to create a test, with specific pcaps?

I wonder if this is more along the lines of what you are looking for - https://github.com/secureworks/dalton

**Comment by javabeanz** [comment]
good suggestion, ill give that a try.

**Comment by jasonish** [comment]
Closing issue as this is not really the purpose of Suricata-Verify. 

Also archiving this repo as its now been moved to https://github.com/OISF/suricata-verify.
